from pathlib import Path
from pytest_bdd_report.extensions.screenshot import screenshot_repo


def screenshot(
    image: bytes | str | Path, feature_name: str, scenario_name: str
) -> None:
    """
    Attach a screenshot to the report generated by pytest-bdd-report.
    This method accepts an image in bytes or file path and adds it to the report along with the relative feature and scenario.

    Args:
        image (bytes | str | Path): The image data or file path to be attached.
        feature_name (str): The name of the feature for which the screenshot is being attached.
        scenario_name (str): The name of the scenario for which the screenshot is being attached.
    """
    try:
        screenshot_repo.add(feature_name, scenario_name, image)
    except (ValueError, RuntimeWarning) as e:
        print(f"Error while attaching the screenshot: {e}")
