import base64
from pytest_bdd_report.screenshot import screenshot_repo


def screenshot_file(path: str, feature_name: str, scenario_name: str) -> None:
    """
    Attach the screenshot file to the report generated by pytest-bdd-report
    """
    with open(path, 'rb') as image_file:
        image_bytes = image_file.read()
        image_base64 = base64.b64encode(image_bytes).decode('utf-8')
    
    if image_base64:
        screenshot_repo.add(feature_name, scenario_name, image_base64)

def screenshot(image_bytes: bytes, feature_name: str, scenario_name: str) -> None:
    """
    Attach the screenshot to the report generated by pytest-bdd-report
    """
    image_base64 = base64.b64encode(image_bytes).decode('utf-8')
    #TODO vedere se aggiungere un try except
    screenshot_repo.add(feature_name, scenario_name, image_base64)